// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The network command to execute, e.g., "curl -sS https://example.com"
	Command       string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ResetRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StepRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Target IP address (IPv4 as string for now, e.g. "93.184.216.34")
	TargetIp string `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	// Target Port
	TargetPort uint32 `protobuf:"varint,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	// Action variables from RL model
	MaxPacingRate uint32 `protobuf:"varint,4,opt,name=max_pacing_rate,json=maxPacingRate,proto3" json:"max_pacing_rate,omitempty"` // pacing rate in bytes per second
	SndCwndClamp  uint32 `protobuf:"varint,5,opt,name=snd_cwnd_clamp,json=sndCwndClamp,proto3" json:"snd_cwnd_clamp,omitempty"`    // congestion window clamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StepRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StepRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *StepRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *StepRequest) GetMaxPacingRate() uint32 {
	if x != nil {
		return x.MaxPacingRate
	}
	return 0
}

func (x *StepRequest) GetSndCwndClamp() uint32 {
	if x != nil {
		return x.SndCwndClamp
	}
	return 0
}

type StepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the network command has completed
	Done          bool         `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Observation   *Observation `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StepResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type Observation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RemoteIp   string                 `protobuf:"bytes,1,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	RemotePort uint32                 `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// Metrics captured via eBPF
	SrttUs        uint32 `protobuf:"varint,3,opt,name=srtt_us,json=srttUs,proto3" json:"srtt_us,omitempty"`                      // Smoothed RTT in microseconds
	MdevUs        uint32 `protobuf:"varint,4,opt,name=mdev_us,json=mdevUs,proto3" json:"mdev_us,omitempty"`                      // Mean deviation in microseconds
	TotalRetrans  uint32 `protobuf:"varint,5,opt,name=total_retrans,json=totalRetrans,proto3" json:"total_retrans,omitempty"`    // Total retransmissions
	BytesSent     uint64 `protobuf:"varint,6,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`             // Total bytes sent
	BytesReceived uint64 `protobuf:"varint,7,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"` // Total bytes received
	DurationUs    uint64 `protobuf:"varint,8,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`          // Connection duration in microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Observation) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *Observation) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *Observation) GetSrttUs() uint32 {
	if x != nil {
		return x.SrttUs
	}
	return 0
}

func (x *Observation) GetMdevUs() uint32 {
	if x != nil {
		return x.MdevUs
	}
	return 0
}

func (x *Observation) GetTotalRetrans() uint32 {
	if x != nil {
		return x.TotalRetrans
	}
	return 0
}

func (x *Observation) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Observation) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *Observation) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"(\n" +
	"\fResetRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"b\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xb8\x01\n" +
	"\vStepRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttarget_ip\x18\x02 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\rR\n" +
	"targetPort\x12&\n" +
	"\x0fmax_pacing_rate\x18\x04 \x01(\rR\rmaxPacingRate\x12$\n" +
	"\x0esnd_cwnd_clamp\x18\x05 \x01(\rR\fsndCwndClamp\"X\n" +
	"\fStepResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x124\n" +
	"\vobservation\x18\x02 \x01(\v2\x12.agent.ObservationR\vobservation\"\x89\x02\n" +
	"\vObservation\x12\x1b\n" +
	"\tremote_ip\x18\x01 \x01(\tR\bremoteIp\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\rR\n" +
	"remotePort\x12\x17\n" +
	"\asrtt_us\x18\x03 \x01(\rR\x06srttUs\x12\x17\n" +
	"\amdev_us\x18\x04 \x01(\rR\x06mdevUs\x12#\n" +
	"\rtotal_retrans\x18\x05 \x01(\rR\ftotalRetrans\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x06 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\a \x01(\x04R\rbytesReceived\x12\x1f\n" +
	"\vduration_us\x18\b \x01(\x04R\n" +
	"durationUs2o\n" +
	"\bEnvAgent\x122\n" +
	"\x05Reset\x12\x13.agent.ResetRequest\x1a\x14.agent.ResetResponse\x12/\n" +
	"\x04Step\x12\x12.agent.StepRequest\x1a\x13.agent.StepResponseB'Z%socket-tuner/env-ebpf-agent/pkg/pb;pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_proto_goTypes = []any{
	(*ResetRequest)(nil),  // 0: agent.ResetRequest
	(*ResetResponse)(nil), // 1: agent.ResetResponse
	(*StepRequest)(nil),   // 2: agent.StepRequest
	(*StepResponse)(nil),  // 3: agent.StepResponse
	(*Observation)(nil),   // 4: agent.Observation
}
var file_agent_proto_depIdxs = []int32{
	4, // 0: agent.StepResponse.observation:type_name -> agent.Observation
	0, // 1: agent.EnvAgent.Reset:input_type -> agent.ResetRequest
	2, // 2: agent.EnvAgent.Step:input_type -> agent.StepRequest
	1, // 3: agent.EnvAgent.Reset:output_type -> agent.ResetResponse
	3, // 4: agent.EnvAgent.Step:output_type -> agent.StepResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
