// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfIpPortKey struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint32
}

type BpfTuningAction struct {
	_             structs.HostLayout
	MaxPacingRate uint32
	SndCwndClamp  uint32
	CongAlgo      uint32
	InitCwnd      uint32
	WindowClamp   uint32
	NoDelay       uint32
	RtoMin        uint32
	RetransAfter  uint32
	EnableEcn     uint8
	PacingStatus  uint8
	_             [2]byte
	KeepaliveIdle uint32
}

type BpfTuningMetrics struct {
	_             structs.HostLayout
	SrttUs        uint32
	TotalRetrans  uint32
	BytesSent     uint64
	BytesReceived uint64
	StartTimeNs   uint64
	DurationUs    uint64
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	BpfSockmap *ebpf.ProgramSpec `ebpf:"bpf_sockmap"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	ActionMap  *ebpf.MapSpec `ebpf:"action_map"`
	MetricsMap *ebpf.MapSpec `ebpf:"metrics_map"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	ActionMap  *ebpf.Map `ebpf:"action_map"`
	MetricsMap *ebpf.Map `ebpf:"metrics_map"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.ActionMap,
		m.MetricsMap,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	BpfSockmap *ebpf.Program `ebpf:"bpf_sockmap"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.BpfSockmap,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpf.o
var _BpfBytes []byte
