# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x1f\n\x0cResetRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"v\n\rResetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12/\n\x13initial_observation\x18\x04 \x01(\x0b\x32\x12.agent.Observation\"\xb3\x02\n\x0bStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\ttarget_ip\x18\x02 \x01(\t\x12\x13\n\x0btarget_port\x18\x03 \x01(\r\x12\x17\n\x0fmax_pacing_rate\x18\x04 \x01(\r\x12\x16\n\x0esnd_cwnd_clamp\x18\x05 \x01(\r\x12\x11\n\tcong_algo\x18\x06 \x01(\r\x12\x11\n\tinit_cwnd\x18\x07 \x01(\r\x12\x14\n\x0cwindow_clamp\x18\x08 \x01(\r\x12\x10\n\x08no_delay\x18\t \x01(\r\x12\x0f\n\x07rto_min\x18\n \x01(\r\x12\x15\n\rretrans_after\x18\x0b \x01(\r\x12\x12\n\nenable_ecn\x18\x0c \x01(\r\x12\x15\n\rpacing_status\x18\r \x01(\r\x12\x16\n\x0ekeepalive_idle\x18\x0e \x01(\r\"E\n\x0cStepResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\'\n\x0bobservation\x18\x02 \x01(\x0b\x32\x12.agent.Observation\"\xaf\x01\n\x0bObservation\x12\x11\n\tremote_ip\x18\x01 \x01(\t\x12\x13\n\x0bremote_port\x18\x02 \x01(\r\x12\x0f\n\x07srtt_us\x18\x03 \x01(\r\x12\x0f\n\x07mdev_us\x18\x04 \x01(\r\x12\x15\n\rtotal_retrans\x18\x05 \x01(\r\x12\x12\n\nbytes_sent\x18\x06 \x01(\x04\x12\x16\n\x0e\x62ytes_received\x18\x07 \x01(\x04\x12\x13\n\x0b\x64uration_us\x18\x08 \x01(\x04\"\"\n\x0c\x43loseRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\" \n\rCloseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa3\x01\n\x08\x45nvAgent\x12\x32\n\x05Reset\x12\x13.agent.ResetRequest\x1a\x14.agent.ResetResponse\x12/\n\x04Step\x12\x12.agent.StepRequest\x1a\x13.agent.StepResponse\x12\x32\n\x05\x43lose\x12\x13.agent.CloseRequest\x1a\x14.agent.CloseResponseB#Z!socket-tuner/env-router/pkg/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!socket-tuner/env-router/pkg/pb;pb'
  _globals['_RESETREQUEST']._serialized_start=22
  _globals['_RESETREQUEST']._serialized_end=53
  _globals['_RESETRESPONSE']._serialized_start=55
  _globals['_RESETRESPONSE']._serialized_end=173
  _globals['_STEPREQUEST']._serialized_start=176
  _globals['_STEPREQUEST']._serialized_end=483
  _globals['_STEPRESPONSE']._serialized_start=485
  _globals['_STEPRESPONSE']._serialized_end=554
  _globals['_OBSERVATION']._serialized_start=557
  _globals['_OBSERVATION']._serialized_end=732
  _globals['_CLOSEREQUEST']._serialized_start=734
  _globals['_CLOSEREQUEST']._serialized_end=768
  _globals['_CLOSERESPONSE']._serialized_start=770
  _globals['_CLOSERESPONSE']._serialized_end=802
  _globals['_ENVAGENT']._serialized_start=805
  _globals['_ENVAGENT']._serialized_end=968
# @@protoc_insertion_point(module_scope)
