apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: socket-tuner
  region: us-east-1
  version: "1.34"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single

managedNodeGroups:
  - name: system-nodes
    instanceType: t3.small
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    privateNetworking: true
    amiFamily: AmazonLinux2023
    labels:
      role: system
    tags:
      karpenter.sh/discovery: socket-tuner

addons:
  - name: coredns
  - name: kube-proxy
  - name: vpc-cni
