// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: env-router/proto/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnvAgent_Reset_FullMethodName = "/agent.EnvAgent/Reset"
	EnvAgent_Step_FullMethodName  = "/agent.EnvAgent/Step"
	EnvAgent_Close_FullMethodName = "/agent.EnvAgent/Close"
)

// EnvAgentClient is the client API for EnvAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvAgentClient interface {
	// Reset the environment: prepare a new network command scenario
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Take an action: apply eBPF socket tuning and return resulting metrics
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
	// Explicitly end the session and release the agent
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type envAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvAgentClient(cc grpc.ClientConnInterface) EnvAgentClient {
	return &envAgentClient{cc}
}

func (c *envAgentClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, EnvAgent_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envAgentClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, EnvAgent_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envAgentClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, EnvAgent_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvAgentServer is the server API for EnvAgent service.
// All implementations must embed UnimplementedEnvAgentServer
// for forward compatibility.
type EnvAgentServer interface {
	// Reset the environment: prepare a new network command scenario
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	// Take an action: apply eBPF socket tuning and return resulting metrics
	Step(context.Context, *StepRequest) (*StepResponse, error)
	// Explicitly end the session and release the agent
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	mustEmbedUnimplementedEnvAgentServer()
}

// UnimplementedEnvAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvAgentServer struct{}

func (UnimplementedEnvAgentServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedEnvAgentServer) Step(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedEnvAgentServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedEnvAgentServer) mustEmbedUnimplementedEnvAgentServer() {}
func (UnimplementedEnvAgentServer) testEmbeddedByValue()                  {}

// UnsafeEnvAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvAgentServer will
// result in compilation errors.
type UnsafeEnvAgentServer interface {
	mustEmbedUnimplementedEnvAgentServer()
}

func RegisterEnvAgentServer(s grpc.ServiceRegistrar, srv EnvAgentServer) {
	// If the following call panics, it indicates UnimplementedEnvAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvAgent_ServiceDesc, srv)
}

func _EnvAgent_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvAgentServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvAgent_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvAgentServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvAgent_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvAgentServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvAgent_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvAgentServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvAgent_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvAgentServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvAgent_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvAgentServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvAgent_ServiceDesc is the grpc.ServiceDesc for EnvAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.EnvAgent",
	HandlerType: (*EnvAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reset",
			Handler:    _EnvAgent_Reset_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _EnvAgent_Step_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _EnvAgent_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "env-router/proto/agent.proto",
}
